<?php
return array(
	'name' => 'Редиректы',
	'description' => 'Продвинутый менеджер редиректов',
	'img' => 'img/seoredirect2.png',
	'version' => '0.0.1',
	'vendor' => 'null',
	'shop_settings' => true,
	'handlers' => array(
		'routing' => 'routing',
		'frontend_head' => 'frontendHead',
		'frontend_error' => 'frontendError',
		'frontend_product' => 'frontendProduct',
		'frontend_category' => 'frontendCategory',
		'backend_category_dialog' => 'backendCategoryDialog',
		'category_delete' => 'categoryDelete',
		'category_save' => 'categorySave',
		'backend_product_edit' => 'backendProductEdit',
		'product_delete' => 'productDelete',
		'product_save' => 'productSave',
		'set_delete' => 'setDelete',
		'set_save' => 'setSave',
		'page_edit' => 'pageEdit',
		'backend_page_edit' => 'backendPageEdit',
		'page_save' => 'pageSave',
		'page_delete' => 'pageEdit',
		'shop_seofilter_filter_save' => 'shopSeofilterFilterSave',
		'shop_seofilter_frontend' => 'shopSeofilterFrontend',
		'frontend_catalogreviews' => 'handleFrontendCatalogreviews',
        'backend_menu' => 'handleBackendMenu',
	),
);
