<?php

return array(
    0 => array(
        'rss-dzen/' => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'feed'),
        'rss-dzen'  => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'feed'),
        '<blog_url>/rss-dzen/' => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'feed'),
        '<blog_url>/rss-dzen'  => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'feed'),
        'blog/rss-dzen/' => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'feed'),
        'blog/rss-dzen'  => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'feed'),
        'blog/<blog_url>/rss-dzen/' => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'feed'),
        'blog/<blog_url>/rss-dzen'  => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'feed'),

        'dzen-api/save/' => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'apiSave'),
        'dzen-api/save'  => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'apiSave'),
        'dzen-api/validate/' => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'validate'),
        'dzen-api/validate'  => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'validate'),
        '<blog_url>/dzen-api/save/' => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'apiSave'),
        '<blog_url>/dzen-api/save'  => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'apiSave'),
        '<blog_url>/dzen-api/validate/' => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'validate'),
        '<blog_url>/dzen-api/validate'  => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'validate'),
        'blog/dzen-api/save/' => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'apiSave'),
        'blog/dzen-api/save'  => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'apiSave'),
        'blog/dzen-api/validate/' => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'validate'),
        'blog/dzen-api/validate'  => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'validate'),
        'blog/<blog_url>/dzen-api/save/' => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'apiSave'),
        'blog/<blog_url>/dzen-api/save'  => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'apiSave'),
        'blog/<blog_url>/dzen-api/validate/' => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'validate'),
        'blog/<blog_url>/dzen-api/validate'  => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'validate'),
    ),
    1 => array(
        'rss-dzen/' => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'feed'),
        'rss-dzen'  => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'feed'),
        '<blog_url>/rss-dzen/' => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'feed'),
        '<blog_url>/rss-dzen'  => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'feed'),
        'blog/rss-dzen/' => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'feed'),
        'blog/rss-dzen'  => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'feed'),
        'blog/<blog_url>/rss-dzen/' => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'feed'),
        'blog/<blog_url>/rss-dzen'  => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'feed'),

        'dzen-api/save/' => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'apiSave'),
        'dzen-api/save'  => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'apiSave'),
        'dzen-api/validate/' => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'validate'),
        'dzen-api/validate'  => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'validate'),
        '<blog_url>/dzen-api/save/' => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'apiSave'),
        '<blog_url>/dzen-api/save'  => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'apiSave'),
        '<blog_url>/dzen-api/validate/' => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'validate'),
        '<blog_url>/dzen-api/validate'  => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'validate'),
        'blog/dzen-api/save/' => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'apiSave'),
        'blog/dzen-api/save'  => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'apiSave'),
        'blog/dzen-api/validate/' => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'validate'),
        'blog/dzen-api/validate'  => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'validate'),
        'blog/<blog_url>/dzen-api/save/' => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'apiSave'),
        'blog/<blog_url>/dzen-api/save'  => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'apiSave'),
        'blog/<blog_url>/dzen-api/validate/' => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'validate'),
        'blog/<blog_url>/dzen-api/validate'  => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'validate'),
    ),
    2 => array(
        'blog/rss-dzen/' => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'feed'),
        'blog/rss-dzen'  => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'feed'),
        'blog/<blog_url>/rss-dzen/' => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'feed'),
        'blog/<blog_url>/rss-dzen'  => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'feed'),
        'rss-dzen/' => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'feed'),
        'rss-dzen'  => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'feed'),
        '<blog_url>/rss-dzen/' => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'feed'),
        '<blog_url>/rss-dzen'  => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'feed'),

        'blog/dzen-api/save/' => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'apiSave'),
        'blog/dzen-api/save'  => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'apiSave'),
        'blog/dzen-api/validate/' => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'validate'),
        'blog/dzen-api/validate'  => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'validate'),
        'blog/<blog_url>/dzen-api/save/' => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'apiSave'),
        'blog/<blog_url>/dzen-api/save'  => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'apiSave'),
        'blog/<blog_url>/dzen-api/validate/' => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'validate'),
        'blog/<blog_url>/dzen-api/validate'  => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'validate'),
        'dzen-api/save/' => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'apiSave'),
        'dzen-api/save'  => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'apiSave'),
        'dzen-api/validate/' => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'validate'),
        'dzen-api/validate'  => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'validate'),
        '<blog_url>/dzen-api/save/' => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'apiSave'),
        '<blog_url>/dzen-api/save'  => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'apiSave'),
        '<blog_url>/dzen-api/validate/' => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'validate'),
        '<blog_url>/dzen-api/validate'  => array('plugin' => 'dzen', 'module' => 'frontend', 'action' => 'validate'),
    ),
);
