<?php
return array(
    'enabled'  => array(
        'title'        => 'Включить панель',
        'description'  => 'Отображать панель навигации на витрине.',
        'control_type' => waHtmlControl::CHECKBOX,
        'value'        => 1,
    ),
    'button_1' => array(
        'title'        => 'Кнопка 1',
        'control_type' => waHtmlControl::SELECT,
        'options'      => array(
            ''           => 'Не использовать',
            'home'       => 'Главная',
            'catalog'    => 'Каталог',
            'cart'       => 'Корзина',
            'favorites'  => 'Избранное',
            'compare'    => 'Сравнение',
            'search'     => 'Поиск',
            'account'    => 'Кабинет',
        ),
        'value'        => 'home',
    ),
    'button_2' => array(
        'title'        => 'Кнопка 2',
        'control_type' => waHtmlControl::SELECT,
        'options'      => array(
            ''           => 'Не использовать',
            'home'       => 'Главная',
            'catalog'    => 'Каталог',
            'cart'       => 'Корзина',
            'favorites'  => 'Избранное',
            'compare'    => 'Сравнение',
            'search'     => 'Поиск',
            'account'    => 'Кабинет',
        ),
        'value'        => 'catalog',
    ),
    'button_3' => array(
        'title'        => 'Кнопка 3',
        'control_type' => waHtmlControl::SELECT,
        'options'      => array(
            ''           => 'Не использовать',
            'home'       => 'Главная',
            'catalog'    => 'Каталог',
            'cart'       => 'Корзина',
            'favorites'  => 'Избранное',
            'compare'    => 'Сравнение',
            'search'     => 'Поиск',
            'account'    => 'Кабинет',
        ),
        'value'        => 'cart',
    ),
    'button_4' => array(
        'title'        => 'Кнопка 4',
        'control_type' => waHtmlControl::SELECT,
        'options'      => array(
            ''           => 'Не использовать',
            'home'       => 'Главная',
            'catalog'    => 'Каталог',
            'cart'       => 'Корзина',
            'favorites'  => 'Избранное',
            'compare'    => 'Сравнение',
            'search'     => 'Поиск',
            'account'    => 'Кабинет',
        ),
        'value'        => 'search',
    ),
    'button_5' => array(
        'title'        => 'Кнопка 5',
        'control_type' => waHtmlControl::SELECT,
        'options'      => array(
            ''           => 'Не использовать',
            'home'       => 'Главная',
            'catalog'    => 'Каталог',
            'cart'       => 'Корзина',
            'favorites'  => 'Избранное',
            'compare'    => 'Сравнение',
            'search'     => 'Поиск',
            'account'    => 'Кабинет',
        ),
        'value'        => 'account',
    ),
    'searchpro_enabled' => array(
        'value'        => 0,
        'title'        => 'Интеграция с ПоискПРО',
        'description'  => 'Заменять форму поиска на ПоискПРО, если плагин установлен.',
        'control_type' => waHtmlControl::CHECKBOX
    ),
);
